# Using Pandas to Explore COVID-19 Data

```{r, echo = F}
library(reticulate)
```

## Plans for this section

In the previous two sections, we introduced basics to plotting using `matplotlib` and generating exploratory analysis & visualisations using `pandas`. In this section, we are going to put these skills into practice and explore the COVID19 dataset from GitHub (https://github.com/datasets/covid-19) that is maintained by Johns Hopkins University.

## Housekeeping

It is always good to get a rough idea about a dataset, right at the start.

<!-- Exercise -->
`r my_fun.exercise('What are we dealing with?')`

```{python,results='asis',echo=F,cache=F}
from my_functions import render_python
print(render_python('covid-housekeeping1.py'))
```


<!-- Exercise -->
`r my_fun.exercise('Drop those unnecessary columns?')`

```{python,results='asis',echo=F,cache=F}
from my_functions import render_python
print(render_python('covid-housekeeping2.py'))
```

<!-- Exercise -->
`r my_fun.exercise('Subset to ASEAN countries only')`

```{python,results='asis',echo=F,cache=F}
from my_functions import render_python
print(render_python('covid-subset-asean.py'))
```

## Exploration of COVID19 dataset: Bar Chart

<!-- Exercise -->
`r my_fun.exercise('Plotting the Total Deaths in each country')`

```{python,results='asis',echo=F,cache=F}
from my_functions import render_python
print(render_python('covid-barchart.py'))
```

## Exploration of COVID19 dataset: Time-Series

<!-- Exercise -->
`r my_fun.exercise('Total Confirmed Cases in each country over time')`

```{python,results='asis',echo=F,cache=F}
from my_functions import render_python
print(render_python('covid-time-series.py'))
```

## Exploration of COVID19 dataset: Time-Series Daily Cases

<!-- Exercise -->
`r my_fun.exercise('Daily Confirmed Cases in each country over time')`

```{python,results='asis',echo=F,cache=F}
from my_functions import render_python
print(render_python('covid-time-series-daily.py'))
```
