# Using Pandas to Explore Data

Here we will be using pandas to do some exploratory plots on a dataset containing `Gender`, `Height` and, `Weight`. The dataset we are going to be using is an edited version from (Kaggle)[https://www.kaggle.com/mustafaali96/weight-height/version/1] where we trimmed to 200 total rows and converted everything to the metric system.

## Barcharts

`r my_fun.example('Barcharts with error bars')`

#### Result {-}

Nothing here yet.

#### Code {-}

- `df.agg` function applies various functions to a data set.
- `yerr` in `df.plot` applies error bars to the bar chart.

```{python,eval=F}
# Import relevant packages
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

plt.cla()
plt.subplots(figsize = (10,7))

# Reading in the dataset as df
df = pd.read_csv("https://raw.githubusercontent.com/nus-sps/workshops.tfi.data-visualisation/main/files/height-weight-metric.csv")

# Creating a function to calculate standard error
def se(data):
    return np.std(data) / np.sqrt(data.count())

# Grouping the data set of "Height" by Gender
grouped_gender = df.groupby("Gender")['Height']

# Applying functions np.mean() and se() to our grouped dataset
new_df = grouped_gender.agg([np.mean, se])

new_df.plot(kind = 'bar', yerr = 'se',capsize=10, rot=0)

# Don't forget to add the labels for clarity!
plt.ylabel('Average Height (cm)', fontsize = 10)
plt.xlabel('Gender', fontsize = 10)
plt.title('Average Height (cm) vs Gender', fontsize = 20)
plt.legend().remove
plt.tight_layout()
plt.show()
```

## Histograms

`r my_fun.example('Histograms with Grouping')`

#### Result (No Group){-}

Nothing here yet.

#### Code (No Group) {-}

- Note the use of `kind = hist` to generate histograms.

```{python,eval=F}
# Import relevant packages
import pandas as pd
import matplotlib.pyplot as plt

plt.cla()
plt.subplots(figsize = (10,7))

# Reading in the dataset as df
df = pd.read_csv("https://raw.githubusercontent.com/nus-sps/workshops.tfi.data-visualisation/main/files/height-weight-metric.csv")

df['Height'].plot(kind='hist')


# Label your axis
plt.ylabel('Frequency', fontsize = 10)
plt.xlabel('Height (cm)', fontsize = 10)
plt.title('Histogram of Height (cm)', fontsize = 20)
plt.tight_layout()
plt.legend()
plt.show()
```

#### Result (Grouped){-}

Nothing here yet.

#### Code (Grouped) {-}

- Note the use of `alpha = 0.5` to generate semi-transparent histograms.
- This would help to get your messages across!

```{python,eval=F}
# Import relevant packages
import pandas as pd
import matplotlib.pyplot as plt

plt.cla()
plt.subplots(figsize = (10,7))

# Reading in the dataset as df
df = pd.read_csv("https://raw.githubusercontent.com/nus-sps/workshops.tfi.data-visualisation/main/files/height-weight-metric.csv")

grouped_gender = df.groupby("Gender")['Height']
grouped_gender.plot(kind='hist', alpha = 0.5, bins = 15)


# Label your axis
plt.ylabel('Frequency', fontsize = 10)
plt.xlabel('Height (cm)', fontsize = 10)
plt.title('Histogram of Height (cm) grouped by Gender', fontsize = 20)
plt.tight_layout()
plt.legend()
plt.show()
```

## Scatterplots

`r my_fun.example('Grouped Scatterplots')`

#### Result (No Group){-}

Nothing here yet.

#### Code (No Group){-}

- Recall on the use of `for loops` and `ax` plotting in `matplotlib`.

```{python,eval=F}
# Import relevant packages
import pandas as pd
import matplotlib.pyplot as plt

plt.cla()
plt.subplots(figsize = (10,7))

# Reading in the dataset as df
df = pd.read_csv("https://raw.githubusercontent.com/nus-sps/workshops.tfi.data-visualisation/main/files/height-weight-metric.csv")


df.plot("Height", 'Weight', kind='scatter')

# Label your axis
plt.xlabel('Height (cm)', fontsize = 10)
plt.ylabel('Weight (kg)', fontsize = 10)
plt.title('Weight (kg) vs Height (cm)', fontsize = 20)
plt.tight_layout()
plt.legend()
plt.show()
```

#### Result (Grouped){-}

Nothing here yet.

#### Code (Grouped){-}

- Recall on the use of `for loops` and `ax` plotting in `matplotlib`.

```{python,eval=F}
# Import relevant packages
import pandas as pd
import matplotlib.pyplot as plt

plt.cla()
plt.subplots(figsize = (10,7))

# Reading in the dataset as df
df = pd.read_csv("https://raw.githubusercontent.com/nus-sps/workshops.tfi.data-visualisation/main/files/height-weight-metric.csv")

grouped_gender = df.groupby("Gender")

# Calling plt.subplots().
fig, ax = plt.subplots()

for name, gender in grouped_gender:
    ax.scatter(gender["Height"], gender["Weight"], label=name)


# Label your axis
plt.xlabel('Height (cm)', fontsize = 10)
plt.ylabel('Weight (kg)', fontsize = 10)
plt.title('Weight (kg) vs Height (cm) grouped by Gender', fontsize = 20)
plt.tight_layout()
plt.legend()
plt.show()
```

## Boxplots

`r my_fun.example('Boxplots')`

#### Result {-}

Nothing here yet.

#### Code {-}

- Note the use of `df.boxplot` for boxplot instead of `df.plot`.
- For our purposes `plt.suptitle('')` was used to remove the secondary title of our boxplot.

```{python,eval=F}
# Import relevant packages
import pandas as pd
import matplotlib.pyplot as plt

plt.cla()
plt.subplots(figsize = (10,7))

# Reading in the dataset as df
df = pd.read_csv("https://raw.githubusercontent.com/nus-sps/workshops.tfi.data-visualisation/main/files/height-weight-metric.csv")

#Plotting boxplot
ax = df.boxplot('Height', by='Gender')
ax.grid(False)

# Don't forget to add the labels for clarity!
plt.suptitle('')
plt.title('Boxplot of Height (cm) grouped by Gender', fontsize = 20)
plt.ylabel('Height (cm)', fontsize = 10)
plt.xlabel('Gender', fontsize = 10)
plt.tight_layout()
plt.show()
```